public enum TokenType {
    //Datatypes
    THOUGHT, NEURON, SYNAPSE, PULSE, SPARK, STREAM, CLUSTER, VOID, INSTINCT,

    //Control Flow
    STIMULATE, INHIBIT, EVALUATE, PATH, BASE, CYCLE, REACT, ECHO, DORMANT, FLOW, RECALL,

    //PROGRAM STRUCTURE
    ACTIVATE, ACTION,

    //INPUT&OUTPUT
    SENSE, EXPRESS,

    //STRING OPERATIONS
    TRANSCRIBE, LENGTH,

    //OPERATORS
    UNARY_OP, EXP_OP, MUL_OP, ADD_OP, REL_OP, EQUALITY_OP, AND_OP, XOR_OP, OR_OP, ASSIGN_OP, //categorized based on precedence

    //SEPERATOR & GROUPING SYMBOLS
    L_PAREN, R_PAREN, L_BRACE, R_BRACE, L_BRACKET, R_BRACKET, COMMA, SEMICOLON, COLON,

    //BOOLEANS
    TRUE, FALSE,

    //USER DEFINED TOKENS & LITERALS
    IDENTIFIER, PULSE_LIT, SPARK_LIT, STREAM_LIT, NEURON_LIT, THOUGHT_LIT,

    //SPECIAL TOKEN
    EOF,
    ILLEGAL
}
